sequenceDiagram
    participant browser
    participant server

    browser ->> server: GET: https://studies.cs.helsinki.fi/exampleapp/notes
    activate server
    server ->> browser: HTML Files
    deactivate server

    browser ->> server: GET: https://studies.cs.helsinki.fi/exampleapp/main.css
    activate server
    server ->> browser: CSS Files
    deactivate server

    browser ->> server: GET: https://studies.cs.helsinki.fi/exampleapp/main.js
    activate server
    server ->> browser: JS Files
    deactivate server

    browser ->> server: GET: https://studies.cs.helsinki.fi/exampleapp/data.json
    activate server
    server ->> browser: JSON Files [{"content": "-", "date": "2025-02-10T06:40:26.224Z"}...]
    deactivate server

    Notes right of browser: the browser submit the form to the server which is then redirect back to notes causing 3 more HTTPS request.
    browser ->> server: POST: https://studies.cs.helsinki.fi/exampleapp/new_note
    activate server
    server ->> browser: 302 Redirect to the "/exampleapp/notes"

    Notes right of browser: Reloading the webpage after the POST for the form means re-fetching the files.
    browser ->> server: GET: https://studies.cs.helsinki.fi/exampleapp/notes
    activate server
    server ->> browser: HTML Files
    deactivate server

    browser ->> server: GET: https://studies.cs.helsinki.fi/exampleapp/main.css
    activate server
    server ->> browser: CSS Files
    deactivate server

    browser ->> server: GET: https://studies.cs.helsinki.fi/exampleapp/main.js
    activate server
    server ->> browser: JS Files
    deactivate server

    browser ->> server: GET: https://studies.cs.helsinki.fi/exampleapp/data.json
    activate server
    server ->> browser: JSON Files [{"content": "-", "date": "2025-02-10T06:40:26.224Z"}...]
    deactivate server
